language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '11'
script:
  - npm run lint
  - npm run test
  # End to End test like
  - node index.js lodash -r 2 && node index.js lodash bluebird react
after_script:
  - npm run publish-coverage
