language: node_js
node_js:
  - '8'
  - '10'
  - '12'
script:
  - npm test
  # End to End test like
  - node index.js lodash -r 2 && node index.js lodash bluebird react
after_script:
  - npm run publish-coverage
